# 置換したい環境変数のキーを配列で定義
const ENV_KEYS* = [
  "ADDPERM:DISCORD_WEBHOOK",
  "BANPLAYERSHEET:API_URL",
  "BUNGEEGUARD:ALLOWED_TOKENS",
  "DISCORDSRV:BOT_TOKEN",
  "DISCORDSRV:CHANNELS",
  "DISCORDSRV:CONSOLE_CHANNEL_ID",
  "TPSLOG:DISCORD_WEBHOOK"
]
